import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { once } from "node:events";
import { fixture, textNode, privateNode, privateData } from "./helpers.js";
import { resolveTarget, isPublicAddress } from "../src/egress.js";

test("sessions require origin and CSRF; invitations, views and mutations are authorized", async (t) => {
  const f = await fixture(t);
  const ownerUser = await f.user("owner", true), viewerUser = await f.user("viewer"), strangerUser = await f.user("stranger");
  const owner = await f.login(ownerUser), viewer = await f.login(viewerUser), stranger = await f.login(strangerUser);
  const room = await f.room(owner);
  assert.equal((await f.request("GET", `/api/rooms/${room.id}`)).status, 401);
  assert.equal((await f.request("GET", `/api/rooms/${room.id}`, undefined, stranger)).status, 404);
  assert.equal((await f.request("POST", "/api/rooms", { title: "x" }, owner, { origin: "https://attacker.example" })).status, 403);
  const missingCsrf = await f.app.inject({ method: "POST", url: "/api/rooms", payload: { title: "x" }, headers: { origin: f.config.APP_ORIGIN, cookie: owner.cookie } });
  assert.equal(missingCsrf.statusCode, 403);
  assert.match(owner.cookie, /^canvas_session=/);
  const invite = await f.share(room.id, owner, "viewer", { password: "invitation-password" });
  assert.equal((await f.joinRoom(invite, viewer)).status, 403);
  assert.equal((await f.request("POST", "/api/shares/join", { token: invite.token, password: "invitation-password" }, viewer)).status, 200);
  assert.equal((await f.send(room.id, viewer, [{ type: "create", node: textNode() }])).status, 403);
  assert.equal((await f.request("POST", `/api/rooms/${room.id}/shares`, { role: "editor" }, viewer)).status, 403);
  assert.equal((await f.request("GET", "/api/admin/status", undefined, viewer)).status, 403);
  const socket = f.socket(room.id, viewer); await socket.ready;
  const closed = once(socket.ws, "close");
  assert.equal((await f.request("DELETE", `/api/rooms/${room.id}/shares/${invite.id}`, undefined, owner)).status, 200);
  assert.equal((await closed)[0], 4001);
  assert.equal((await f.request("GET", `/api/rooms/${room.id}`, undefined, viewer)).status, 404);
  assert.equal((await f.joinRoom(invite, viewer)).status, 403);
  const wrongOrigin = f.socket(room.id, owner, "https://attacker.example");
  await assert.rejects(wrongOrigin.ready, /403/);
  assert.equal((await f.request("POST", "/api/auth/logout", undefined, owner)).status, 200);
  assert.equal((await f.request("GET", "/api/auth/session", undefined, owner)).status, 401);
});

test("private payloads stay out of snapshots, websockets, logs and other owners' access", async (t) => {
  const f = await fixture(t, {}, { executeRequest: async () => ({ status: 200, text: "private-result-value" }) });
  const owner = await f.login(await f.user("owner", true)), editor = await f.login(await f.user("editor"));
  const room = await f.room(owner);
  await f.joinRoom(await f.share(room.id, owner), editor);
  const connection = f.socket(room.id, owner); await connection.ready;
  const node = privateNode();
  assert.equal((await f.send(room.id, editor, [{ type: "create", node }])).status, 200);
  const publicSnapshot = await f.request("GET", `/api/rooms/${room.id}`, undefined, owner);
  const serialized = JSON.stringify(publicSnapshot.body);
  for (const secret of ["Confidential", "test-private-api-key", "request-body", "api.example.com"]) assert.ok(!serialized.includes(secret));
  assert.deepEqual(Object.keys(publicSnapshot.body.nodes[0]).sort(), ["id", "kind", "position", "width", "height", "title", "content", "fileId", "version"].sort());
  assert.equal(publicSnapshot.body.nodes[0].title, "隐私节点");
  assert.equal((await f.request("GET", `/api/rooms/${room.id}/private/${node.id}`, undefined, owner)).status, 404);
  assert.equal((await f.send(room.id, owner, [{ type: "delete", id: node.id, version: 1 }])).status, 403);
  assert.equal((await f.send(room.id, editor, [{ type: "update", id: node.id, version: 1, fields: { content: "accidental-secret" } }])).status, 400);
  const privatePath = `/api/rooms/${room.id}/private/${node.id}`;
  const own = await f.request("GET", privatePath, undefined, editor);
  assert.equal(own.body.data.request.apiKey, "test-private-api-key");
  assert.equal(own.response.headers["cache-control"], "no-store");
  assert.equal((await f.request("PUT", privatePath, { version: 1, data: privateData("updated-secret") }, editor)).status, 200);
  assert.equal((await f.request("PUT", privatePath, { version: 1, data: privateData("stale-secret") }, editor)).status, 409);
  assert.equal((await f.request("POST", `${privatePath}/run`, { version: 2 }, editor)).status, 200);
  const other = await f.request("GET", `/api/rooms/${room.id}`, undefined, owner);
  assert.ok(!JSON.stringify(other.body).includes("private-result-value"));
  const raw = await f.app.context.db.get("SELECT private_cipher,result_cipher FROM nodes WHERE id=?", [node.id]);
  assert.ok(!JSON.stringify(raw).includes("updated-secret"));
  assert.ok(!JSON.stringify(raw).includes("private-result-value"));
  const audits = await f.app.context.db.all("SELECT * FROM audit");
  assert.ok(!JSON.stringify(audits).includes("private-result-value"));
  assert.ok(!JSON.stringify(connection.events).includes("Confidential"));
  assert.ok(!JSON.stringify(connection.events).includes("test-private-api-key"));
  const fields = { ...textNode(), privateData: privateData() };
  assert.equal((await f.send(room.id, editor, [{ type: "create", node: fields }])).status, 400);
  connection.ws.close();
});

test("optimistic versions and idempotent receipts prevent lost or duplicate writes", async (t) => {
  const f = await fixture(t);
  const owner = await f.login(await f.user("owner"));
  const room = await f.room(owner), node = textNode();
  const operationId = randomUUID(), create = [{ type: "create", node }];
  const first = await f.send(room.id, owner, create, operationId);
  const duplicate = await f.send(room.id, owner, create, operationId);
  assert.deepEqual(first.body, duplicate.body);
  assert.equal((await f.send(room.id, owner, [{ type: "create", node: textNode() }], operationId)).status, 409);
  const replies = await Promise.all(["one", "two"].map((content) => f.send(room.id, owner, [{ type: "update", id: node.id, version: 1, fields: { content } }])));
  assert.deepEqual(replies.map((r) => r.status).sort(), [200, 409]);
  const unchanged = await f.send(room.id, owner, [{ type: "update", id: node.id, version: 2, fields: { title: "should-rollback" } }, { type: "delete", id: randomUUID(), version: 1 }]);
  assert.equal(unchanged.status, 409);
  const snapshot = (await f.request("GET", `/api/rooms/${room.id}`, undefined, owner)).body;
  assert.equal(snapshot.nodes[0].title, node.title);
  assert.equal(snapshot.nodes[0].version, 2);
  assert.equal(snapshot.revision, 2);
  const overLimit = await f.app.inject({ method: "POST", url: `/api/rooms/${room.id}/operations`, headers: { origin: f.config.APP_ORIGIN, cookie: owner.cookie, "x-csrf-token": owner.csrf, "content-type": "application/json" }, payload: JSON.stringify({ content: "x".repeat(f.config.MAX_SYNC_BYTES) }) });
  assert.equal(overLimit.statusCode, 413);
});

test("registration needs a current invitation and never grants owner or administrator access", async (t) => {
  const f = await fixture(t);
  const owner = await f.login(await f.user("owner", true));
  const room = await f.room(owner);
  const share = await f.share(room.id, owner, "viewer");
  const registered = await f.request("POST", "/api/auth/register", { username: "new-user", password: "new-member-long-password", inviteToken: share.token });
  assert.equal(registered.status, 200);
  assert.equal(registered.body.user.admin, false);
  assert.equal(registered.body.roomId, room.id);
  assert.equal((await f.request("POST", "/api/auth/register", { username: "bad-user", password: "new-member-long-password", inviteToken: "bad-token" })).status, 403);
  await f.app.context.db.run("UPDATE shares SET expires_at=? WHERE id=?", [Date.now() - 1, share.id]);
  assert.equal((await f.request("POST", "/api/auth/register", { username: "expired", password: "new-member-long-password", inviteToken: share.token })).status, 403);
});

test("egress blocks SSRF and validates every DNS answer before pinning", async () => {
  for (const ip of ["127.0.0.1", "10.0.0.1", "169.254.169.254", "172.16.0.1", "192.168.1.1", "::1", "::ffff:127.0.0.1", "fc00::1", "fe80::1", "100.100.100.200", "0.0.0.0"]) assert.equal(isPublicAddress(ip), false, ip);
  assert.equal(isPublicAddress("8.8.8.8"), true);
  const publicDns = async () => [{ address: "8.8.8.8", family: 4 }];
  for (const url of ["http://api.example.com", "https://api.example.com:8443", "https://user:pass@api.example.com", "https://other.example.com", "file:///etc/passwd"]) await assert.rejects(resolveTarget(url, ["api.example.com"], publicDns));
  await assert.rejects(resolveTarget("https://api.example.com", ["api.example.com"], async () => [{ address: "8.8.8.8", family: 4 }, { address: "127.0.0.1", family: 4 }]));
  const approved = await resolveTarget("https://api.example.com/v1", ["api.example.com"], publicDns);
  assert.equal(approved.address.address, "8.8.8.8");
});
